<a href="https://colab.research.google.com/github/kalidindiraju/07-01-25/blob/main/20-01-25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np



In [6]:
a=np.random.randint(30,99,(7,8))
a

array([[31, 77, 59, 77, 70, 95, 74, 49],
       [75, 50, 80, 83, 56, 68, 47, 37],
       [42, 71, 32, 31, 39, 60, 52, 80],
       [83, 35, 67, 94, 30, 98, 52, 54],
       [33, 59, 49, 92, 89, 64, 98, 31],
       [90, 32, 47, 84, 44, 48, 83, 97],
       [43, 37, 58, 78, 58, 83, 63, 36]])

In [13]:
a[1:5,1:6]

array([[50, 80, 83, 56, 68],
       [71, 32, 31, 39, 60],
       [35, 67, 94, 30, 98],
       [59, 49, 92, 89, 64]])

In [14]:
import pandas as pd

In [17]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [21]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [31]:
pd.Series(k) #only for one dimensional data

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [26]:
t=np.array(k)
t

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [36]:
k=[[4, 7], [2, 9], [7, 3], [90, 50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [37]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [43]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df #2 dimensio

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [44]:
df.columns

Index(['name', 'sub'], dtype='object')

In [45]:
df['sub'].mean()

17.25

In [46]:
df['sub'].median()

8.0

In [47]:
df['sub'].max()



50

In [48]:
df['sub'].quantile(0.25)

6.0

In [49]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64